name: Bash Cleanup Tool CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          if command -v brew >/dev/null 2>&1; then
            brew install shellcheck coreutils
          else
            sudo apt-get update
            sudo apt-get install -y shellcheck
          fi

      - name: Lint script
        run: shellcheck src/cleanup-by-date

      - name: Run tests
        run: make test
